### ISSUE TITLE
ValueError: Requesting negative frame numbers not allowed

### ISSUE THREAD

**Issue by theChaosCoder** [Endilll/vapoursynth-preview#1]
I'm on frame 8 (N-frame is set to 10). I click on "Seek N frames backwards"

```
VSPreview is not tested on PyQt5 versions prior to 5.12, but you have 5.11.3. Use at your own risk.
2019-03-23 12:29:21.618: INFO: No storage found. Using defaults.
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\vapoursynth-preview-master\vspreview\toolbars\playback.py", line 173, in seek_n_frames_b
    self.main.current_frame -= FrameInterval(self.seek_frame_spinbox.value())  # type: ignore
  File "C:\Python37\Lib\site-packages\vapoursynth-preview-master\vspreview\main.py", line 568, in current_frame
    self.on_current_frame_changed(value)
  File "C:\Python37\Lib\site-packages\vapoursynth-preview-master\vspreview\main.py", line 520, in on_current_frame_changed
    self.current_output.graphics_scene_item.setPixmap(self.render_frame(frame, self.current_output))
  File "C:\Python37\Lib\site-packages\vapoursynth-preview-master\vspreview\main.py", line 481, in render_frame
    return self.render_raw_videoframe(output.vs_output.get_frame(int(frame)))
  File "src\cython\vapoursynth.pyx", line 1223, in vapoursynth.VideoNode.get_frame
  File "src\cython\vapoursynth.pyx", line 1215, in vapoursynth.VideoNode.ensure_valid_frame_number
ValueError: Requesting negative frame numbers not allowed
```

Same problem with "Seek N frames Forward". But in this case it gets stuck and crashes if I click on play.

**Comment by Endilll** [comment]
I can't get myself to proper testing. Thanks
