### ISSUE TITLE
Cannot start vspreview: no attribute 'AlphaOutputTuple'

### ISSUE THREAD

**Issue by capric98** [Endilll/vapoursynth-preview#42]
macOS Monterey arm64, brew installed pyqt@5 = 5.15.4
Should I install a R53 version of vapoursynth instead?

```
$ python3 -V
Python 3.9.7

$ vspipe -v
VapourSynth Video Processing Library
Copyright (c) 2012-2021 Fredrik Mellbin
Core R57
API R4.0
API R3.6
Options: -

$ python3 -m pip install -U git+https://github.com/Endilll/vapoursynth-preview.git
...

$ python3 -m vspreview ~/Documents/test.vpy
2021-11-03 20:47:24.660: DEBUG: Reading QSS file in: :qdarkstyle/dark/style.qss
2021-11-03 20:47:24.661: INFO: QSS file sucessfuly loaded.
2021-11-03 20:47:24.661: DEBUG: Checking patches for being applied.
2021-11-03 20:47:24.661: INFO: Found OS patches to be applied.
2021-11-03 20:47:24.661: INFO: Found version patches to be applied.
2021-11-03 20:47:24.661: INFO: Found application patches to be applied.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/vspreview/models/outputs.py", line 37, in __init__
    output = local_storage[str(i)]
KeyError: '0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.9/site-packages/vspreview/__main__.py", line 2, in <module>
    main()
  File "/opt/homebrew/lib/python3.9/site-packages/vspreview/main.py", line 844, in main
    main_window.load_script(script_path, external_args=args.external_args)
  File "/opt/homebrew/lib/python3.9/site-packages/vspreview/main.py", line 547, in load_script
    self.toolbars.main.rescan_outputs()
  File "/opt/homebrew/lib/python3.9/site-packages/vspreview/main.py", line 201, in rescan_outputs
    self.outputs = Outputs()
  File "/opt/homebrew/lib/python3.9/site-packages/vspreview/models/outputs.py", line 40, in __init__
    output = Output(vs_output, i)
  File "/opt/homebrew/lib/python3.9/site-packages/vspreview/core/types.py", line 696, in __init__
    if isinstance(vs_output, vs.AlphaOutputTuple):
AttributeError: module 'vapoursynth' has no attribute 'AlphaOutputTuple'
```

**Comment by Ichunjo** [comment]
https://github.com/Endilll/vapoursynth-preview/issues/31

**Comment by capric98** [comment]
> #31

Thanks, it helps!
https://github.com/Endilll/vapoursynth-preview/issues/31#issuecomment-932738785
https://github.com/DJATOM/LibP2P-Vapoursynth
